- name: Launch AWS cluster
  hosts: localhost
  connection: local
  gather_facts: false
  tasks: 
    - name: Launch cloudformation cluster via ansible
      cloudformation: 
        stack_name: "zetta-coreos"
        state: "present"
        region: "us-east-1"
        template: "../aws/cloud-formation.json"
        template_parameters:
          InstanceType: "t1.micro"
          ClusterSize: 5
          DiscoveryURL: "https://discovery.etcd.io/f42233a3a5d15446dfd6832565f1eed1"
          BuiltCoreOSAMI: "ami-589ac730"
        tags:
          Stack: "Zetta Core"
