- name: setting up a singe zetta docker container
  hosts: zetta
  tasks:
    - name: "Copying zetta service file"
      copy: src=./services/zetta@.service dest=/home/core

    - name: "Copying zetta sidekick service"
      copy: src=./services/zmon@.service dest=/home/core

    - name: "Copying zetta-service-registry"
      copy: src=./services/zetta-registry@.service dest=/home/core

    - name: "Copying zetta-cloud-proxy"
      copy: src=./services/zetta-proxy@.service dest=/home/core

    - name: "Copying zetta-target-server"
      copy: src=./services/zetta-target@.service dest=/home/core
