- name: setting up a influxdb cluster
  hosts: zetta
  tasks:
    - name: "Copying influx service"
      copy: src=./services/influxdb@.service dest=/home/core

    - name: "Copying influx sidekick"
      copy: src=./services/influxdb-discovery@.service dest=/home/core

    - name: "Copying influx setup script"
      copy: src=./scripts/setup_influxdb.sh dest=/home/core

    - name: "Submitting influxdb service file"
      raw: fleetctl submit /home/core/influxdb@.service

    - name: "Submitting influxdb-discovery service file"
      raw: fleetctl submit /home/core/influxdb-discovery@.service

    - name: "Starting Influxdb Master"
      raw: fleetctl start influxdb@1 influxdb-discovery@1 && while [ $(etcdctl ls /services/influxdb/seed 2> /dev/null | wc -l) -lt 1 ]; do echo "Waiting for influxdb to start..."; sleep 1; done;

    - name: "Starting Influxdb Replicas"
      raw: echo fleetctl start influxdb\@{2..`fleetctl list-machines | tail -n +2 | wc -l`} influxdb-discovery\@{2..`fleetctl list-machines | tail -n +2 | wc -l`} | bash

    - name: "Setup Influx Database"
      raw: bash /home/core/setup_influxdb.sh test-db -r 3 -s 1
